use ImporteInventario
go

IF NOT EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'TBL_IMPORTES_AGENTES')
BEGIN
	CREATE TABLE TBL_IMPORTES_AGENTES 
	(
		ID_AGENTE INT IDENTITY,
		NUMERO_AGENTE INT, 
		AGENTE VARCHAR(200),
		NOMBRE_AGENTE VARCHAR(300),
		CONTRASENA VARBINARY(MAX),
		CORREO VARCHAR(MAX),
		TEL_CELULAR VARCHAR(MAX),
		ID_TIPO_USUARIO INT,
		ID_DE_SUCURSAL INT,
		FECHA_ALTA DATETIME
	)
END

SELECT * FROM TBL_IMPORTES_AGENTES

--DROP TABLE TBL_IMPORTES_AGENTES