use ImporteInventario
go

--select * from TBL_IMPORTES_USUARIOS 

exec SP_INVENTARIO_REGISTRAR_USUARIO 'INV_AGENTE1', 'Abcde1', 'isaarze@hotmail.es','7861308624',2,1
select * from TBL_IMPORTES_USUARIOS 
--select * from CAT_INVENTARIO_TIPOS_USUARIOS

select CONTRASENA,ImporteInventario.dbo.FN_INVENTARIO_DESCIFRAR_CONTRASENA(CONTRASENA) from TBL_IMPORTES_USUARIOS where NUM_USUARIO = 4002